// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260501020339_v1")]
    partial class v1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Models.FormaFarmaceutica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("estado");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.ToTable("formas_farmaceuticas");
                });

            modelBuilder.Entity("Models.Lote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CantidadInicial")
                        .HasColumnType("integer")
                        .HasColumnName("cantidad_inicial");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("codigo");

                    b.Property<int>("DetalleRecepcionId")
                        .HasColumnType("integer")
                        .HasColumnName("detalle_recepcion_id");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("estado");

                    b.Property<DateOnly>("FechaIngreso")
                        .HasColumnType("date")
                        .HasColumnName("fecha_ingreso");

                    b.Property<DateOnly>("FechaVencimiento")
                        .HasColumnType("date")
                        .HasColumnName("fecha_vencimiento");

                    b.Property<int>("MedicamentoId")
                        .HasColumnType("integer")
                        .HasColumnName("medicamento_id");

                    b.HasKey("Id");

                    b.HasIndex("MedicamentoId");

                    b.ToTable("lotes");
                });

            modelBuilder.Entity("Models.Medicamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("codigo");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("estado");

                    b.Property<int>("FormaId")
                        .HasColumnType("integer")
                        .HasColumnName("forma_id");

                    b.Property<int>("MedicamentoId")
                        .HasColumnType("integer")
                        .HasColumnName("medicamento_id");

                    b.Property<int>("UnidadMedidaId")
                        .HasColumnType("integer")
                        .HasColumnName("unidad_medida_id");

                    b.Property<decimal>("ValorConcentracion")
                        .HasColumnType("numeric")
                        .HasColumnName("valor_concentracion");

                    b.HasKey("Id");

                    b.HasIndex("FormaId");

                    b.HasIndex("MedicamentoId");

                    b.HasIndex("UnidadMedidaId");

                    b.ToTable("medicamentos");
                });

            modelBuilder.Entity("Models.Movimiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer")
                        .HasColumnName("cantidad");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("codigo");

                    b.Property<int>("EntidadReferenciaId")
                        .HasColumnType("integer")
                        .HasColumnName("entidad_referencia_id");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("estado");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("observaciones");

                    b.Property<int>("StockActualId")
                        .HasColumnType("integer")
                        .HasColumnName("stock_actual_id");

                    b.Property<int>("TipoMovimientoId")
                        .HasColumnType("integer")
                        .HasColumnName("tipo_movimiento_id");

                    b.HasKey("Id");

                    b.HasIndex("StockActualId");

                    b.HasIndex("TipoMovimientoId");

                    b.ToTable("movimientos");
                });

            modelBuilder.Entity("Models.StockActual", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer")
                        .HasColumnName("cantidad");

                    b.Property<int>("LoteId")
                        .HasColumnType("integer")
                        .HasColumnName("lote_id");

                    b.Property<int>("UbicacionId")
                        .HasColumnType("integer")
                        .HasColumnName("ubicacion_id");

                    b.HasKey("Id");

                    b.HasIndex("LoteId");

                    b.HasIndex("UbicacionId");

                    b.ToTable("stock_actual");
                });

            modelBuilder.Entity("Models.TipoMedicamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("codigo");

                    b.Property<bool>("EsControlado")
                        .HasColumnType("boolean")
                        .HasColumnName("es_controlado");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("estado");

                    b.Property<string>("NombreComercial")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre_comercial");

                    b.Property<string>("NombreGenerico")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre_generico");

                    b.Property<bool>("RequiereRefrigeracion")
                        .HasColumnType("boolean")
                        .HasColumnName("requiere_refrigeracion");

                    b.Property<int>("StockMinimoAlerta")
                        .HasColumnType("integer")
                        .HasColumnName("stock_minimo_alerta");

                    b.HasKey("Id");

                    b.ToTable("tipos_medicamentos");
                });

            modelBuilder.Entity("Models.TipoMovimiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<bool>("EsSuma")
                        .HasColumnType("boolean")
                        .HasColumnName("es_suma");

                    b.HasKey("Id");

                    b.ToTable("tipos_movimiento");
                });

            modelBuilder.Entity("Models.TipoUnidadMedida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Abreviatura")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("abreviatura");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("estado");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.ToTable("tipos_unidad_medida");
                });

            modelBuilder.Entity("Models.UbicacionAlmacen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("codigo");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("estado");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.ToTable("ubicaciones_almacen");
                });

            modelBuilder.Entity("Models.Lote", b =>
                {
                    b.HasOne("Models.Medicamento", "Medicamento")
                        .WithMany()
                        .HasForeignKey("MedicamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medicamento");
                });

            modelBuilder.Entity("Models.Medicamento", b =>
                {
                    b.HasOne("Models.FormaFarmaceutica", "FormaFarmaceutica")
                        .WithMany("Medicamentos")
                        .HasForeignKey("FormaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.TipoMedicamento", "TipoMedicamento")
                        .WithMany("MedicamentosDetallados")
                        .HasForeignKey("MedicamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.TipoUnidadMedida", "TipoUnidadMedida")
                        .WithMany("Medicamentos")
                        .HasForeignKey("UnidadMedidaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FormaFarmaceutica");

                    b.Navigation("TipoMedicamento");

                    b.Navigation("TipoUnidadMedida");
                });

            modelBuilder.Entity("Models.Movimiento", b =>
                {
                    b.HasOne("Models.StockActual", "StockActual")
                        .WithMany("Movimientos")
                        .HasForeignKey("StockActualId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.TipoMovimiento", "TipoMovimiento")
                        .WithMany("Movimientos")
                        .HasForeignKey("TipoMovimientoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StockActual");

                    b.Navigation("TipoMovimiento");
                });

            modelBuilder.Entity("Models.StockActual", b =>
                {
                    b.HasOne("Models.Lote", "Lote")
                        .WithMany("Stocks")
                        .HasForeignKey("LoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.UbicacionAlmacen", "Ubicacion")
                        .WithMany("Stocks")
                        .HasForeignKey("UbicacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lote");

                    b.Navigation("Ubicacion");
                });

            modelBuilder.Entity("Models.FormaFarmaceutica", b =>
                {
                    b.Navigation("Medicamentos");
                });

            modelBuilder.Entity("Models.Lote", b =>
                {
                    b.Navigation("Stocks");
                });

            modelBuilder.Entity("Models.StockActual", b =>
                {
                    b.Navigation("Movimientos");
                });

            modelBuilder.Entity("Models.TipoMedicamento", b =>
                {
                    b.Navigation("MedicamentosDetallados");
                });

            modelBuilder.Entity("Models.TipoMovimiento", b =>
                {
                    b.Navigation("Movimientos");
                });

            modelBuilder.Entity("Models.TipoUnidadMedida", b =>
                {
                    b.Navigation("Medicamentos");
                });

            modelBuilder.Entity("Models.UbicacionAlmacen", b =>
                {
                    b.Navigation("Stocks");
                });
#pragma warning restore 612, 618
        }
    }
}
