// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260505002740_v3.2")]
    partial class v32
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Models.DetalleRecepcion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CantidadRecibida")
                        .HasColumnType("integer")
                        .HasColumnName("cantidad_recibida");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("estado");

                    b.Property<DateOnly>("FechaVencimiento")
                        .HasColumnType("date")
                        .HasColumnName("fecha_vencimiento");

                    b.Property<int>("MedicamentoId")
                        .HasColumnType("integer")
                        .HasColumnName("medicamento_id");

                    b.Property<int>("RecepcionId")
                        .HasColumnType("integer")
                        .HasColumnName("recepcion_id");

                    b.HasKey("Id");

                    b.HasIndex("MedicamentoId");

                    b.HasIndex("RecepcionId");

                    b.ToTable("detalle_recepcion");
                });

            modelBuilder.Entity("Models.DetalleReceta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CantidadSolicitada")
                        .HasColumnType("integer")
                        .HasColumnName("cantidad_solicitada");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("estado");

                    b.Property<int>("MedicamentoId")
                        .HasColumnType("integer")
                        .HasColumnName("medicamento_id");

                    b.Property<int>("RecetaId")
                        .HasColumnType("integer")
                        .HasColumnName("receta_id");

                    b.HasKey("Id");

                    b.HasIndex("MedicamentoId");

                    b.HasIndex("RecetaId");

                    b.ToTable("detalle_receta");
                });

            modelBuilder.Entity("Models.Dispensacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("codigo");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("estado");

                    b.Property<string>("FarmaceuticoCodigo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("farmaceutico_codigo");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<string>("QuienRecoge")
                        .HasColumnType("text")
                        .HasColumnName("quien_recoge");

                    b.Property<int>("RecetaId")
                        .HasColumnType("integer")
                        .HasColumnName("receta_id");

                    b.HasKey("Id");

                    b.HasIndex("RecetaId");

                    b.ToTable("dispensacion");
                });

            modelBuilder.Entity("Models.DispensacionLote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CantidadEntregada")
                        .HasColumnType("integer")
                        .HasColumnName("cantidad_entregada");

                    b.Property<int>("DetalleRecetaId")
                        .HasColumnType("integer")
                        .HasColumnName("detalle_receta_id");

                    b.Property<int>("DispensacionId")
                        .HasColumnType("integer")
                        .HasColumnName("dispensacion_id");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("estado");

                    b.Property<int>("StockActualId")
                        .HasColumnType("integer")
                        .HasColumnName("stock_actual_id");

                    b.HasKey("Id");

                    b.HasIndex("DetalleRecetaId");

                    b.HasIndex("DispensacionId");

                    b.HasIndex("StockActualId");

                    b.ToTable("dispensacion_lote");
                });

            modelBuilder.Entity("Models.FormaFarmaceutica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("estado");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.ToTable("formas_farmaceuticas");
                });

            modelBuilder.Entity("Models.Lote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CantidadInicial")
                        .HasColumnType("integer")
                        .HasColumnName("cantidad_inicial");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("codigo");

                    b.Property<int>("DetalleRecepcionId")
                        .HasColumnType("integer")
                        .HasColumnName("detalle_recepcion_id");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("estado");

                    b.Property<DateOnly>("FechaIngreso")
                        .HasColumnType("date")
                        .HasColumnName("fecha_ingreso");

                    b.Property<int>("MedicamentoId")
                        .HasColumnType("integer")
                        .HasColumnName("medicamento_id");

                    b.HasKey("Id");

                    b.HasIndex("DetalleRecepcionId");

                    b.HasIndex("MedicamentoId");

                    b.ToTable("lotes");
                });

            modelBuilder.Entity("Models.Medicamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("codigo");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("estado");

                    b.Property<int>("FormaId")
                        .HasColumnType("integer")
                        .HasColumnName("forma_id");

                    b.Property<int>("MedicamentoId")
                        .HasColumnType("integer")
                        .HasColumnName("medicamento_id");

                    b.Property<int>("UnidadMedidaId")
                        .HasColumnType("integer")
                        .HasColumnName("unidad_medida_id");

                    b.Property<decimal>("ValorConcentracion")
                        .HasColumnType("numeric")
                        .HasColumnName("valor_concentracion");

                    b.HasKey("Id");

                    b.HasIndex("FormaId");

                    b.HasIndex("MedicamentoId");

                    b.HasIndex("UnidadMedidaId");

                    b.ToTable("medicamentos");
                });

            modelBuilder.Entity("Models.Movimiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer")
                        .HasColumnName("cantidad");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("codigo");

                    b.Property<int>("EntidadReferenciaId")
                        .HasColumnType("integer")
                        .HasColumnName("entidad_referencia_id");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("estado");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text")
                        .HasColumnName("observaciones");

                    b.Property<int>("StockActualId")
                        .HasColumnType("integer")
                        .HasColumnName("stock_actual_id");

                    b.Property<int>("TipoMovimientoId")
                        .HasColumnType("integer")
                        .HasColumnName("tipo_movimiento_id");

                    b.HasKey("Id");

                    b.HasIndex("StockActualId");

                    b.HasIndex("TipoMovimientoId");

                    b.ToTable("movimientos");
                });

            modelBuilder.Entity("Models.Posologia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("codigo");

                    b.Property<int>("DetalleRecetaId")
                        .HasColumnType("integer")
                        .HasColumnName("detalle_receta_id");

                    b.Property<decimal>("Dosis")
                        .HasColumnType("numeric")
                        .HasColumnName("dosis");

                    b.Property<string>("Duracion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("duracion");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("estado");

                    b.Property<string>("Frecuencia")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("frecuencia");

                    b.Property<int>("FrecuenciaValor")
                        .HasColumnType("integer")
                        .HasColumnName("frecuencia_valor");

                    b.Property<string>("IndicacionesAdicionales")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("indicaciones_adicionales");

                    b.Property<string>("UnidadMedida")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("unidad_medida");

                    b.Property<string>("ViaAdministracion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("via_administracion");

                    b.HasKey("Id");

                    b.HasIndex("DetalleRecetaId")
                        .IsUnique();

                    b.ToTable("posologias");
                });

            modelBuilder.Entity("Models.Recepcion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("codigo");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("estado");

                    b.Property<DateOnly>("FechaRecepcion")
                        .HasColumnType("date")
                        .HasColumnName("fecha_recepcion");

                    b.Property<string>("RecibidoPorCodigo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("recibido_por_codigo");

                    b.HasKey("Id");

                    b.ToTable("recepciones");
                });

            modelBuilder.Entity("Models.Receta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("codigo");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("estado");

                    b.Property<DateOnly>("FechaSolicitud")
                        .HasColumnType("date")
                        .HasColumnName("fecha_solicitud");

                    b.Property<string>("MedicoCodigo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("medico_codigo");

                    b.Property<string>("PacienteCodigo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("paciente_codigo");

                    b.HasKey("Id");

                    b.ToTable("recetas");
                });

            modelBuilder.Entity("Models.StockActual", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer")
                        .HasColumnName("cantidad");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("estado");

                    b.Property<int>("LoteId")
                        .HasColumnType("integer")
                        .HasColumnName("lote_id");

                    b.Property<int>("UbicacionId")
                        .HasColumnType("integer")
                        .HasColumnName("ubicacion_id");

                    b.HasKey("Id");

                    b.HasIndex("LoteId");

                    b.HasIndex("UbicacionId");

                    b.ToTable("stock_actual");
                });

            modelBuilder.Entity("Models.TipoMedicamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("codigo");

                    b.Property<bool>("EsControlado")
                        .HasColumnType("boolean")
                        .HasColumnName("es_controlado");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("estado");

                    b.Property<string>("NombreComercial")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre_comercial");

                    b.Property<string>("NombreGenerico")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre_generico");

                    b.Property<bool>("RequiereRefrigeracion")
                        .HasColumnType("boolean")
                        .HasColumnName("requiere_refrigeracion");

                    b.Property<int>("StockMinimoAlerta")
                        .HasColumnType("integer")
                        .HasColumnName("stock_minimo_alerta");

                    b.HasKey("Id");

                    b.ToTable("tipos_medicamentos");
                });

            modelBuilder.Entity("Models.TipoMovimiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<bool>("EsSuma")
                        .HasColumnType("boolean")
                        .HasColumnName("es_suma");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("estado");

                    b.HasKey("Id");

                    b.ToTable("tipos_movimiento");
                });

            modelBuilder.Entity("Models.TipoUnidadMedida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Abreviatura")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("abreviatura");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("estado");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.ToTable("tipos_unidad_medida");
                });

            modelBuilder.Entity("Models.UbicacionAlmacen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("codigo");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("estado");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.ToTable("ubicaciones_almacen");
                });

            modelBuilder.Entity("Models.DetalleRecepcion", b =>
                {
                    b.HasOne("Models.Medicamento", "Medicamento")
                        .WithMany()
                        .HasForeignKey("MedicamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.Recepcion", "Recepcion")
                        .WithMany("Detalles")
                        .HasForeignKey("RecepcionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medicamento");

                    b.Navigation("Recepcion");
                });

            modelBuilder.Entity("Models.DetalleReceta", b =>
                {
                    b.HasOne("Models.Medicamento", "Medicamento")
                        .WithMany()
                        .HasForeignKey("MedicamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.Receta", "Receta")
                        .WithMany("Detalles")
                        .HasForeignKey("RecetaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medicamento");

                    b.Navigation("Receta");
                });

            modelBuilder.Entity("Models.Dispensacion", b =>
                {
                    b.HasOne("Models.Receta", "Receta")
                        .WithMany("Dispensaciones")
                        .HasForeignKey("RecetaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Receta");
                });

            modelBuilder.Entity("Models.DispensacionLote", b =>
                {
                    b.HasOne("Models.DetalleReceta", "DetalleReceta")
                        .WithMany("DispensacionesLote")
                        .HasForeignKey("DetalleRecetaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.Dispensacion", "Dispensacion")
                        .WithMany("DispensacionLotes")
                        .HasForeignKey("DispensacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.StockActual", "StockActual")
                        .WithMany()
                        .HasForeignKey("StockActualId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DetalleReceta");

                    b.Navigation("Dispensacion");

                    b.Navigation("StockActual");
                });

            modelBuilder.Entity("Models.Lote", b =>
                {
                    b.HasOne("Models.DetalleRecepcion", "DetalleRecepcion")
                        .WithMany("Lotes")
                        .HasForeignKey("DetalleRecepcionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.Medicamento", "Medicamento")
                        .WithMany()
                        .HasForeignKey("MedicamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DetalleRecepcion");

                    b.Navigation("Medicamento");
                });

            modelBuilder.Entity("Models.Medicamento", b =>
                {
                    b.HasOne("Models.FormaFarmaceutica", "FormaFarmaceutica")
                        .WithMany("Medicamentos")
                        .HasForeignKey("FormaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.TipoMedicamento", "TipoMedicamento")
                        .WithMany("MedicamentosDetallados")
                        .HasForeignKey("MedicamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.TipoUnidadMedida", "TipoUnidadMedida")
                        .WithMany("Medicamentos")
                        .HasForeignKey("UnidadMedidaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FormaFarmaceutica");

                    b.Navigation("TipoMedicamento");

                    b.Navigation("TipoUnidadMedida");
                });

            modelBuilder.Entity("Models.Movimiento", b =>
                {
                    b.HasOne("Models.StockActual", "StockActual")
                        .WithMany("Movimientos")
                        .HasForeignKey("StockActualId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.TipoMovimiento", "TipoMovimiento")
                        .WithMany("Movimientos")
                        .HasForeignKey("TipoMovimientoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StockActual");

                    b.Navigation("TipoMovimiento");
                });

            modelBuilder.Entity("Models.Posologia", b =>
                {
                    b.HasOne("Models.DetalleReceta", "DetalleReceta")
                        .WithOne("Posologia")
                        .HasForeignKey("Models.Posologia", "DetalleRecetaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DetalleReceta");
                });

            modelBuilder.Entity("Models.StockActual", b =>
                {
                    b.HasOne("Models.Lote", "Lote")
                        .WithMany("Stocks")
                        .HasForeignKey("LoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.UbicacionAlmacen", "Ubicacion")
                        .WithMany("Stocks")
                        .HasForeignKey("UbicacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lote");

                    b.Navigation("Ubicacion");
                });

            modelBuilder.Entity("Models.DetalleRecepcion", b =>
                {
                    b.Navigation("Lotes");
                });

            modelBuilder.Entity("Models.DetalleReceta", b =>
                {
                    b.Navigation("DispensacionesLote");

                    b.Navigation("Posologia")
                        .IsRequired();
                });

            modelBuilder.Entity("Models.Dispensacion", b =>
                {
                    b.Navigation("DispensacionLotes");
                });

            modelBuilder.Entity("Models.FormaFarmaceutica", b =>
                {
                    b.Navigation("Medicamentos");
                });

            modelBuilder.Entity("Models.Lote", b =>
                {
                    b.Navigation("Stocks");
                });

            modelBuilder.Entity("Models.Recepcion", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("Models.Receta", b =>
                {
                    b.Navigation("Detalles");

                    b.Navigation("Dispensaciones");
                });

            modelBuilder.Entity("Models.StockActual", b =>
                {
                    b.Navigation("Movimientos");
                });

            modelBuilder.Entity("Models.TipoMedicamento", b =>
                {
                    b.Navigation("MedicamentosDetallados");
                });

            modelBuilder.Entity("Models.TipoMovimiento", b =>
                {
                    b.Navigation("Movimientos");
                });

            modelBuilder.Entity("Models.TipoUnidadMedida", b =>
                {
                    b.Navigation("Medicamentos");
                });

            modelBuilder.Entity("Models.UbicacionAlmacen", b =>
                {
                    b.Navigation("Stocks");
                });
#pragma warning restore 612, 618
        }
    }
}
