// <auto-generated />
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260426231719_v0")]
    partial class v0
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Models.FormaFarmaceutica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("estado");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.ToTable("formas_farmaceuticas");
                });

            modelBuilder.Entity("Models.Medicamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("codigo");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("estado");

                    b.Property<int>("FormaId")
                        .HasColumnType("integer")
                        .HasColumnName("forma_id");

                    b.Property<int>("MedicamentoId")
                        .HasColumnType("integer")
                        .HasColumnName("medicamento_id");

                    b.Property<int>("UnidadMedidaId")
                        .HasColumnType("integer")
                        .HasColumnName("unidad_medida_id");

                    b.Property<decimal>("ValorConcentracion")
                        .HasColumnType("numeric")
                        .HasColumnName("valor_concentracion");

                    b.HasKey("Id");

                    b.HasIndex("FormaId");

                    b.HasIndex("MedicamentoId");

                    b.HasIndex("UnidadMedidaId");

                    b.ToTable("medicamentos");
                });

            modelBuilder.Entity("Models.TipoMedicamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("codigo");

                    b.Property<bool>("EsControlado")
                        .HasColumnType("boolean")
                        .HasColumnName("es_controlado");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("estado");

                    b.Property<string>("NombreComercial")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre_comercial");

                    b.Property<string>("NombreGenerico")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre_generico");

                    b.Property<bool>("RequiereRefrigeracion")
                        .HasColumnType("boolean")
                        .HasColumnName("requiere_refrigeracion");

                    b.Property<int>("StockMinimoAlerta")
                        .HasColumnType("integer")
                        .HasColumnName("stock_minimo_alerta");

                    b.HasKey("Id");

                    b.ToTable("tipos_medicamentos");
                });

            modelBuilder.Entity("Models.TipoUnidadMedida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Abreviatura")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("abreviatura");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("estado");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.ToTable("tipos_unidad_medida");
                });

            modelBuilder.Entity("Models.Medicamento", b =>
                {
                    b.HasOne("Models.FormaFarmaceutica", "FormaFarmaceutica")
                        .WithMany("Medicamentos")
                        .HasForeignKey("FormaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.TipoMedicamento", "TipoMedicamento")
                        .WithMany("MedicamentosDetallados")
                        .HasForeignKey("MedicamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.TipoUnidadMedida", "TipoUnidadMedida")
                        .WithMany("Medicamentos")
                        .HasForeignKey("UnidadMedidaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FormaFarmaceutica");

                    b.Navigation("TipoMedicamento");

                    b.Navigation("TipoUnidadMedida");
                });

            modelBuilder.Entity("Models.FormaFarmaceutica", b =>
                {
                    b.Navigation("Medicamentos");
                });

            modelBuilder.Entity("Models.TipoMedicamento", b =>
                {
                    b.Navigation("MedicamentosDetallados");
                });

            modelBuilder.Entity("Models.TipoUnidadMedida", b =>
                {
                    b.Navigation("Medicamentos");
                });
#pragma warning restore 612, 618
        }
    }
}
